apiVersion: v1
kind: Service
metadata:
  name: {{ include "lbrycrd.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "lbrycrd.name" . }}
    helm.sh/chart: {{ include "lbrycrd.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: LoadBalancer
  ports:
    - port: 9245
      targetPort: lbry
      protocol: TCP
      name: lbry
  selector:
    app.kubernetes.io/name: {{ include "lbrycrd.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
