apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.service }}-ingress
  annotations:  
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/cluster-issuer: {{ .Values.certManagerIssuer }}i
spec:
  tls:
  - hosts:
    - {{ .Values.hostname }}
    secretName: {{ .Values.certManagerIssuer }}
  rules:
  - host: {{ .Values.hostname }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.service }}
          servicePort: 80
